<a href="https://colab.research.google.com/github/ztokar/Pytorch-tutorial/blob/main/Intro_to_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+2

4

In [13]:
import torch

In [2]:
import numpy as np

In [4]:
my_list=[1,2,3,4,5]
my_list2=[[1,2,3],[4,5,6]]  #python lists

In [11]:
np1=np.random.rand(3,4)
np1

array([[0.12033084, 0.31301349, 0.07270579, 0.31952114],
       [0.28326613, 0.86676339, 0.60009879, 0.16127247],
       [0.83478039, 0.79384236, 0.92531614, 0.06438301]])

In [7]:
np1.dtype

dtype('float64')

In [18]:
tensor_2d=torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [15]:
tensor_3d=torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [17]:
#Create tensor out of numpy array
my_tensor=torch.tensor(np1)
my_tensor

tensor([[0.1203, 0.3130, 0.0727, 0.3195],
        [0.2833, 0.8668, 0.6001, 0.1613],
        [0.8348, 0.7938, 0.9253, 0.0644]], dtype=torch.float64)