<a href="https://colab.research.google.com/github/ztokar/Pytorch-tutorial/blob/main/Intro_to_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+2

4

In [ ]:
import torch

In [ ]:
import numpy as np

In [ ]:
my_list=[1,2,3,4,5]
my_list2=[[1,2,3],[4,5,6]]  #python lists

In [ ]:
np1=np.random.rand(3,4)
np1

array([[0.12033084, 0.31301349, 0.07270579, 0.31952114],
       [0.28326613, 0.86676339, 0.60009879, 0.16127247],
       [0.83478039, 0.79384236, 0.92531614, 0.06438301]])

In [ ]:
np1.dtype

dtype('float64')

In [ ]:
tensor_2d=torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [ ]:
tensor_3d=torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
#Create tensor out of numpy array
my_tensor=torch.tensor(np1)
my_tensor

tensor([[0.1203, 0.3130, 0.0727, 0.3195],
        [0.2833, 0.8668, 0.6001, 0.1613],
        [0.8348, 0.7938, 0.9253, 0.0644]], dtype=torch.float64)

In [ ]:
my_torch=torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Reshape and view
my_torch=my_torch.reshape(2,5)

In [ ]:
my_torch   #needs to fit the shape

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
#reshape if we don't know the number of items using -1
my_torch2=torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
mytorch2=my_torch2.reshape(-1,2)
mytorch2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
my_torch3=torch.arange(10)
my_torch4=my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch5=torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch6=my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch5[1]=4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [ ]:
my_torch6  #changing in tensor_5

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [ ]:
my_torch7=torch.arange(10)
my_torch7[7]

tensor(7)

In [ ]:
my_torch8=my_torch7.reshape(5,2)

In [ ]:
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
#slices
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [ ]:
#return column as is
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])