<a href="https://colab.research.google.com/github/ztokar/Pytorch-tutorial/blob/main/Pytorch_Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+2

4

In [ ]:
import torch

In [ ]:
import numpy as np

In [ ]:
my_list=[1,2,3,4,5]
my_list2=[[1,2,3],[4,5,6]]  #python lists

In [ ]:
np1=np.random.rand(3,4)
np1

array([[0.12033084, 0.31301349, 0.07270579, 0.31952114],
       [0.28326613, 0.86676339, 0.60009879, 0.16127247],
       [0.83478039, 0.79384236, 0.92531614, 0.06438301]])

In [ ]:
np1.dtype

dtype('float64')

In [ ]:
tensor_2d=torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [ ]:
tensor_3d=torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
#Create tensor out of numpy array
my_tensor=torch.tensor(np1)
my_tensor

tensor([[0.1203, 0.3130, 0.0727, 0.3195],
        [0.2833, 0.8668, 0.6001, 0.1613],
        [0.8348, 0.7938, 0.9253, 0.0644]], dtype=torch.float64)

In [ ]:
my_torch=torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Reshape and view
my_torch=my_torch.reshape(2,5)

In [ ]:
my_torch   #needs to fit the shape

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
#reshape if we don't know the number of items using -1
my_torch2=torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
mytorch2=my_torch2.reshape(-1,2)
mytorch2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
my_torch3=torch.arange(10)
my_torch4=my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch5=torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch6=my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch5[1]=4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [ ]:
my_torch6  #changing in tensor_5

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [ ]:
my_torch7=torch.arange(10)
my_torch7[7]

tensor(7)

In [ ]:
my_torch8=my_torch7.reshape(5,2)

In [ ]:
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
#slices
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [ ]:
#return column as is
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [ ]:
#basic math with tensor
import torch
import numpy as np

In [ ]:
tensor_a=torch.tensor([1,2,3,4])
tensor_b=torch.tensor([5,6,7,8])
tensor_b+tensor_a

tensor([ 6,  8, 10, 12])

In [ ]:
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
tensor_b-tensor_a
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [ ]:
tensor_a*tensor_b
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [ ]:
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
tensor_b % tensor_a
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [ ]:
zz=pow(tensor_a,3)
zz

tensor([ 1,  8, 27, 64])

In [ ]:
tensor_a.add(tensor_b)   #another way to write long hand

tensor([ 6,  8, 10, 12])

In [ ]:
tensor_a.add_(tensor_b)  # the _ reassigns

tensor([ 6,  8, 10, 12])

In [ ]:
tensor_a

tensor([ 6,  8, 10, 12])

In [ ]:
import torch.nn as nn
import torch.nn.functional as F #moves data forward

In [ ]:
#Creates model class that inherits nn.module
class Model(nn.Module):
  #input later (4 features of the flower)--> hidden layer 1 (number of neurons)-->>h2-->output
  #output (3 classes of iris flower)
  def __init__(self,in_features=4,h1=8,h2=9,out_features=3):
    super().__init__() #instantiate our module
    self.fc1=nn.Linear(in_features,h1)
    self.fc2=nn.Linear(h1,h2)
    self.out=nn.Linear(h2,out_features)

  def forward(self,x):
    x=F.relu(self.fc1(x))   #rectified linear unit- converts to 0 or other number
    x=F.relu(self.fc2(x))
    x=self.out(x)

    return x


In [ ]:
torch.manual_seed(41)  #pick a manual seed for randomization
#create an instance of our model
model=Model()

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd


In [ ]:
url= 'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'
my_df=pd.read_csv(url)

In [ ]:
my_df.head()
my_df.describe

<bound method NDFrame.describe of      sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]>

In [ ]:
#Change last column from strings to integers
my_df['variety']=my_df['variety'].replace('Setosa',0.0)
my_df['variety']=my_df['variety'].replace('Versicolor',1.0)
my_df['variety']=my_df['variety'].replace('Virginica',2.0)


In [ ]:
#Train Test Split Set X,y
import numpy
X=my_df.drop('variety',axis=1)
y=my_df['variety']
type(X)


pandas.core.frame.DataFrame

In [ ]:
#Convert to numpy arrays
X=X.values
y=y.values




AttributeError: ignored

In [ ]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
type(X)
type(y)

numpy.ndarray

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
#Run Train Test Split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2,random_state=41)

In [ ]:
# Converting to tensors
X_train=torch.FloatTensor(X_train)
X_test=torch.FloatTensor(X_test)
y_train=torch.LongTensor(y_train)   #long=64 bit integers
y_test=torch.LongTensor(y_test)

In [ ]:
#Set the criterion of model to measure the error, how far off the predictions are from model
criterion=nn.CrossEntropyLoss()
#Choose Adam Optimizer, lr=learning rate (if error doesn't go down after a bit of epochs/iterations )
optimizer=torch.optim.Adam(model.parameters(),lr=0.01) # 1 epoch is an iteration through the model

model.parameters

<bound method Module.parameters of Model(
  (fc1): Linear(in_features=4, out_features=8, bias=True)
  (fc2): Linear(in_features=8, out_features=9, bias=True)
  (out): Linear(in_features=9, out_features=3, bias=True)
)>